# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ecaf3d155f4aea0a2e44aa8f477f1196b81c60f1395f1be029edd28150c20527a61ab3253e1c1cb95268c718b6a6e7d235b527b7b49b6a69693ba9f76dcc482

test:
  secret_key_base: bb300be23bc129a67ff31b7fa8eb353c8a3d7212d5c6e95d2a08cc50edf1566debeba7c694ea27c2cdd1b0638bba71803855da0f9fcca35024b76b59c5a0f3a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
